### ISSUE TITLE
Logo is pointing towards diffrent file named "portfolio.html"

### ISSUE THREAD

**Issue by psycho-pomp** [PreetiPriya-ui/My_Portfolio#1]
Hey,Great work on the website.
but the logo is not working on clicking it redirects to `[](https://preetipriya-ui.github.io/portfolio.html)`  
you can fix it by changing **line 19** of your code.

**Comment by PreetiPriya-ui** [comment]
Thanks for pointing it out. I will fix it soon.  Actually  in my original file HTML page was named as portfolio.html. That's why, this issue has occurred.
